#############################################################################
# Makefile for building: dual_camera
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  dual_camera.pro
# Template: app
# Command: /home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/qt5/qmake CONFIG+=release -o Makefile dual_camera.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe $(OE_QMAKE_CFLAGS) -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe $(OE_QMAKE_CXXFLAGS) -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I$(SDK_PATH_TARGET)/usr/include/libdrm -I$(SDK_PATH_TARGET)/usr/include/omap -I../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5 -I../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets -I../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui -I../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore -I. -I. -I../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++
QMAKE         = /home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = dual_camera1.0.0
DISTDIR = /home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/example-applications/dual-camera-demo-1.0/.tmp/dual_camera1.0.0
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-O1
LIBS          = $(SUBLIBS) -ljpeg -ldrm_omap -ldrm -L/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
SED           = sed
STRIP         = $(OE_QMAKE_STRIP)

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		jpeg.c \
		loopback.c moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		jpeg.o \
		loopback.o \
		moc_mainwindow.o
DIST          = ../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/qconfig.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dcore.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dinput.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dlogic.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquick.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3drender.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3drender_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_compositor.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_compositor_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_concurrent.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_core.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_core_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_dbus.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_dbus_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_declarative.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_declarative_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_gui.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_gui_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_location.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_location_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimedia.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_network.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_network_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_opengl.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_opengl_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_openglextensions.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_positioning.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_positioning_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_printsupport.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qml.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qml_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qmltest.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quick.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quick_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_script.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_script_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_scripttools.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sensors.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sensors_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sql.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sql_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_svg.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_svg_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_testlib.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_testlib_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_waylandclient.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webchannel.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webengine.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webengine_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginecore.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkit.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkit_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_websockets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_websockets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_widgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_widgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xml.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xml_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_zlib_private.pri \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/uic.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		dual_camera.pro mainwindow.h \
		jpeg.h \
		loopback.h main.cpp \
		mainwindow.cpp \
		jpeg.c \
		loopback.c
QMAKE_TARGET  = dual_camera
DESTDIR       = 
TARGET        = dual_camera


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dual_camera.pro ../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf ../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/qconfig.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dcore.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dinput.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dlogic.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquick.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3drender.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3drender_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_compositor.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_compositor_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_concurrent.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_core.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_core_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_dbus.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_dbus_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_declarative.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_declarative_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_gui.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_gui_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_location.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_location_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimedia.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_network.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_network_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_opengl.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_opengl_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_openglextensions.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_positioning.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_positioning_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_printsupport.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qml.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qml_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qmltest.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quick.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quick_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_script.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_script_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_scripttools.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sensors.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sensors_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sql.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sql_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_svg.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_svg_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_testlib.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_testlib_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_waylandclient.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webchannel.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webengine.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webengine_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginecore.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkit.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkit_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_websockets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_websockets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_widgets.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_widgets_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xml.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xml_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_zlib_private.pri \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/uic.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		dual_camera.pro \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/libQt5Widgets.prl \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/libQt5Gui.prl \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/libQt5Core.prl
	$(QMAKE) CONFIG+=release -o Makefile dual_camera.pro
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/qconfig.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dcore.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dcore_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dinput.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dinput_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dlogic.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquick.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquick_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickinput.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickrender.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3drender.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_3drender_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_compositor.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_compositor_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_concurrent.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_concurrent_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_core.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_core_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_dbus.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_dbus_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_declarative.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_declarative_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_gui.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_gui_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_location.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_location_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimedia.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimedia_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_network.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_network_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_opengl.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_opengl_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_openglextensions.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_positioning.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_positioning_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_printsupport.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_printsupport_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qml.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qml_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qmltest.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qmltest_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quick.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quick_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quickwidgets.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_script.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_script_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_scripttools.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_scripttools_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sensors.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sensors_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sql.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_sql_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_svg.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_svg_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_testlib.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_testlib_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_waylandclient.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webchannel.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webchannel_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webengine.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webengine_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginecore.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkit.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkit_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_websockets.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_websockets_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_widgets.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_widgets_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xml.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xml_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../linux-devkit/sysroots/x86_64-arago-linux/mkspecs/modules/qt_lib_zlib_private.pri:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/uic.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf:
dual_camera.pro:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/libQt5Widgets.prl:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/libQt5Gui.prl:
../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) CONFIG+=release -o Makefile dual_camera.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h jpeg.h loopback.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp jpeg.c loopback.c $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QMainWindow \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qmainwindow.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qglobal.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qconfig.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfeatures.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsystemdetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qprocessordetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcompilerdetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtypeinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtypetraits.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qisenum.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsysinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlogging.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qflags.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbasicatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qgenericatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_cxx11.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_gcc.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_msvc.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv7.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv6.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv5.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_ia64.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_x86.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_unix.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qglobalstatic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmutex.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qnumeric.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qversiontagging.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qnamespace.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs_win.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobject.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstring.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qchar.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbytearray.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qrefcount.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qarraydata.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringbuilder.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qalgorithms.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qiterator.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qhashfunctions.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qpair.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbytearraylist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringlist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qregexp.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringmatcher.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcoreevent.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qscopedpointer.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmetatype.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvarlengtharray.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcontainerfwd.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobject_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmargins.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpaintdevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qrect.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsize.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qpoint.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpalette.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qcolor.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qrgb.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qrgba64.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qbrush.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvector.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qmatrix.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpolygon.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qregion.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qdatastream.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qiodevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qline.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qtransform.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpainterpath.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qimage.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpixelformat.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpixmap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qshareddata.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qhash.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfont.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfontmetrics.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfontinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qsizepolicy.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qcursor.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qkeysequence.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qevent.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvariant.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qdebug.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtextstream.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlocale.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qset.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcontiguouscache.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qurl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qurlquery.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfile.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfiledevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qvector2d.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qtouchdevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qtabwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qicon.h \
		mainwindow.h
	/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/qt5//moc $(DEFINES) -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/example-applications/dual-camera-demo-1.0 -I'/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/example-applications/dual-camera-demo-1.0/$(SDK_PATH_TARGET)/usr/include/libdrm' -I'/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/example-applications/dual-camera-demo-1.0/$(SDK_PATH_TARGET)/usr/include/omap' -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5 -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore -I/home/gtbldadm/tools/linaro-2016.02/arm-linux-gnueabihf/include -I/home/gtbldadm/tools/linaro-2016.02/arm-linux-gnueabihf/include/c++/5.3.1 -I/home/gtbldadm/tools/linaro-2016.02/arm-linux-gnueabihf/include/c++/5.3.1/arm-linux-gnueabihf -I/home/gtbldadm/tools/linaro-2016.02/arm-linux-gnueabihf/include/c++/5.3.1/backward -I/home/gtbldadm/tools/linaro-2016.02/lib/gcc/arm-linux-gnueabihf/5.3.1/include -I/home/gtbldadm/tools/linaro-2016.02/lib/gcc/arm-linux-gnueabihf/5.3.1/include-fixed -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all: mainwindow.moc
compiler_moc_source_clean:
	-$(DEL_FILE) mainwindow.moc
mainwindow.moc: mainwindow.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QMainWindow \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qmainwindow.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qglobal.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qconfig.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfeatures.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsystemdetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qprocessordetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcompilerdetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtypeinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtypetraits.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qisenum.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsysinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlogging.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qflags.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbasicatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qgenericatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_cxx11.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_gcc.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_msvc.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv7.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv6.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv5.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_ia64.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_x86.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_unix.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qglobalstatic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmutex.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qnumeric.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qversiontagging.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qnamespace.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs_win.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobject.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstring.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qchar.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbytearray.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qrefcount.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qarraydata.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringbuilder.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qalgorithms.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qiterator.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qhashfunctions.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qpair.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbytearraylist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringlist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qregexp.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringmatcher.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcoreevent.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qscopedpointer.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmetatype.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvarlengtharray.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcontainerfwd.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobject_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmargins.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpaintdevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qrect.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsize.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qpoint.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpalette.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qcolor.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qrgb.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qrgba64.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qbrush.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvector.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qmatrix.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpolygon.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qregion.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qdatastream.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qiodevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qline.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qtransform.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpainterpath.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qimage.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpixelformat.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpixmap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qshareddata.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qhash.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfont.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfontmetrics.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfontinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qsizepolicy.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qcursor.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qkeysequence.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qevent.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvariant.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qdebug.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtextstream.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlocale.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qset.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcontiguouscache.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qurl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qurlquery.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfile.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfiledevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qvector2d.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qtouchdevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qtabwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qicon.h \
		ui_mainwindow.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/QVariant \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QAction \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qaction.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qactiongroup.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QApplication \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qapplication.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcoreapplication.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qeventloop.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qguiapplication.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qinputmethod.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QButtonGroup \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qbuttongroup.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QFrame \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qframe.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QHeaderView \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qheaderview.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractitemview.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qabstractitemmodel.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qitemselectionmodel.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qstyleoption.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qvalidator.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qregularexpression.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qslider.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractslider.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qstyle.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qtabbar.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qrubberband.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QPushButton \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qpushbutton.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractbutton.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QWidget \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/QThread \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qthread.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/QMutex \
		loopback.h \
		mainwindow.cpp
	/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/qt5//moc $(DEFINES) -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/example-applications/dual-camera-demo-1.0 -I'/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/example-applications/dual-camera-demo-1.0/$(SDK_PATH_TARGET)/usr/include/libdrm' -I'/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/example-applications/dual-camera-demo-1.0/$(SDK_PATH_TARGET)/usr/include/omap' -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5 -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui -I/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore -I/home/gtbldadm/tools/linaro-2016.02/arm-linux-gnueabihf/include -I/home/gtbldadm/tools/linaro-2016.02/arm-linux-gnueabihf/include/c++/5.3.1 -I/home/gtbldadm/tools/linaro-2016.02/arm-linux-gnueabihf/include/c++/5.3.1/arm-linux-gnueabihf -I/home/gtbldadm/tools/linaro-2016.02/arm-linux-gnueabihf/include/c++/5.3.1/backward -I/home/gtbldadm/tools/linaro-2016.02/lib/gcc/arm-linux-gnueabihf/5.3.1/include -I/home/gtbldadm/tools/linaro-2016.02/lib/gcc/arm-linux-gnueabihf/5.3.1/include-fixed -I/usr/include mainwindow.cpp -o mainwindow.moc

compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/gvigelet/ti-processor-sdk-linux-am57xx-evm-03.02.00.05/linux-devkit/sysroots/x86_64-arago-linux/usr/bin/qt5//uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qglobal.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qconfig.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfeatures.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsystemdetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qprocessordetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcompilerdetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtypeinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtypetraits.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qisenum.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsysinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlogging.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qflags.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbasicatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qgenericatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_cxx11.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_gcc.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_msvc.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv7.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv6.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv5.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_ia64.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_x86.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_unix.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qglobalstatic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmutex.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qnumeric.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qversiontagging.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QApplication \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qapplication.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcoreapplication.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstring.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qchar.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbytearray.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qrefcount.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qnamespace.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qarraydata.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringbuilder.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobject.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qalgorithms.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qiterator.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qhashfunctions.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qpair.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbytearraylist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringlist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qregexp.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringmatcher.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcoreevent.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qscopedpointer.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmetatype.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvarlengtharray.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcontainerfwd.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobject_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qeventloop.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs_win.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qpoint.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsize.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qcursor.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmargins.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpaintdevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qrect.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpalette.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qcolor.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qrgb.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qrgba64.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qbrush.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvector.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qmatrix.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpolygon.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qregion.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qdatastream.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qiodevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qline.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qtransform.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpainterpath.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qimage.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpixelformat.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpixmap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qshareddata.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qhash.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfont.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfontmetrics.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfontinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qsizepolicy.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qkeysequence.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qevent.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvariant.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qdebug.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtextstream.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlocale.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qset.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcontiguouscache.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qurl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qurlquery.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfile.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfiledevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qvector2d.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qtouchdevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qguiapplication.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qinputmethod.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QLabel \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qlabel.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qframe.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QPushButton \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qpushbutton.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractbutton.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qicon.h \
		mainwindow.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QMainWindow \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qmainwindow.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qtabwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QMainWindow \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qmainwindow.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qglobal.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qconfig.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfeatures.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsystemdetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qprocessordetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcompilerdetection.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtypeinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtypetraits.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qisenum.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsysinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlogging.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qflags.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbasicatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qgenericatomic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_cxx11.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_gcc.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_msvc.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv7.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv6.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv5.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_ia64.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_x86.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qatomic_unix.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qglobalstatic.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmutex.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qnumeric.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qversiontagging.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qnamespace.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs_win.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobject.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstring.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qchar.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbytearray.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qrefcount.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qarraydata.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringbuilder.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qalgorithms.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qiterator.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qhashfunctions.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qpair.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qbytearraylist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringlist.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qregexp.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qstringmatcher.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcoreevent.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qscopedpointer.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmetatype.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvarlengtharray.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcontainerfwd.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qobject_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmargins.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpaintdevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qrect.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsize.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qpoint.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpalette.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qcolor.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qrgb.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qrgba64.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qbrush.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvector.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qmatrix.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpolygon.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qregion.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qdatastream.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qiodevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qline.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qtransform.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpainterpath.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qimage.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpixelformat.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qpixmap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qshareddata.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qhash.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfont.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfontmetrics.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qfontinfo.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qsizepolicy.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qcursor.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qkeysequence.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qevent.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qvariant.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qmap.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qdebug.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qtextstream.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qlocale.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qset.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcontiguouscache.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qurl.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qurlquery.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfile.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qfiledevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qvector2d.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qtouchdevice.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qtabwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qicon.h \
		ui_mainwindow.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/QVariant \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QAction \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qaction.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qactiongroup.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QApplication \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qapplication.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qcoreapplication.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qeventloop.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qguiapplication.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qinputmethod.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QButtonGroup \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qbuttongroup.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QFrame \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qframe.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QHeaderView \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qheaderview.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractitemview.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qabstractitemmodel.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qitemselectionmodel.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qstyleoption.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtGui/qvalidator.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qregularexpression.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qslider.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractslider.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qstyle.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qtabbar.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qrubberband.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QPushButton \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qpushbutton.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/qabstractbutton.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtWidgets/QWidget \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/QThread \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/qthread.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/qt5/QtCore/QMutex \
		loopback.h \
		mainwindow.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

jpeg.o: jpeg.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o jpeg.o jpeg.c

loopback.o: loopback.c $(SDK_PATH_TARGET)/usr/include/omap/omap_drm.h \
		$(SDK_PATH_TARGET)/usr/include/libdrm/drm.h \
		../../linux-devkit/sysroots/armv7ahf-neon-linux-gnueabi/usr/include/libdrm/drm_mode.h \
		$(SDK_PATH_TARGET)/usr/include/libdrm/omap_drmif.h \
		jpeg.h \
		loopback.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o loopback.o loopback.c

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/root || mkdir -p $(INSTALL_ROOT)/home/root
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/root/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/home/root/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/root/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/root/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

